name = "yourpost-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[assets]
directory = "out"

[[routes]]
pattern = "yourpost.app"
zone_name = "yourpost.app"
